#Cursor Feedback
map enter      no_op
map enter      send_text all \r
map backspace  no_op
map backspace  send_text all \x7f
map ctrl+shift+t new_tab_with_cwd
map ctrl+shift+n new_os_with_cwd
# Scrollbar colors
# scrollbar_handle_color  #939ab7
# scrollbar_track_color   #494d64

# URL color when hovering with mouse
# url_color               #f4dbd6

# Kitty window border colors
# active_border_color     #b7bdf8
# inactive_border_color   #6e738d
# bell_border_color       #eed49f

# OS Window titlebar colors
# wayland_titlebar_color system
# macos_titlebar_color system

#Window font configuration
# font_family Datatype UltraCondensed
font_family Iosevka Charon Mono
# font_family Input Mono Compressed
# font_family JetBrainsMono Nerd Font Mono
# font_family Recursive Monospace Casual
bold_font auto
italic_font auto
bold_italic_font auto
font_size 11

# Tab bar colors
# active_tab_foreground   #181926
# active_tab_background   #c6a0f6
# inactive_tab_foreground #cad3f5
# inactive_tab_background #1e2030
# tab_bar_background      #181926
background_opacity 0.75
background_blur 0

# Colors for marks (marked text in the terminal)
# mark1_foreground #24273a
# mark1_background #b7bdf8
# mark2_foreground #24273a
# mark2_background #c6a0f6
# mark3_foreground #24273a
# mark3_background #7dc4e4


# BEGIN_KITTY_THEME
# Kanagawa
include current-theme.conf
# END_KITTY_THEME
