;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;   The README contains a lot of information
;
;==========================================================

[colors]
background = #282A2E
background-alt = #373B41
foreground = #C5C8C6
secondary = #F0C674
primary = #8ABEB7
alert = #A54242
disabled = #707880

[bar/main]
width = 100%
height = 24pt
radius = 15

; dpi = 96

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 3pt

border-size = 4pt
border-color = #00000000

padding-left = 2
padding-right = 2

module-margin = 1

separator = |
separator-foreground = ${colors.disabled}

font-0 = JetBrainsMono Nerd Font;2
font-1 = "Noto Sans CJK JP:size=10;2"
modules-left = powermenu xworkspaces music
modules-center = xwindow
modules-right = filesystem pulseaudio backlight memory cpu wlan eth bluetooth battery date

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

; wm-restack = generic
; wm-restack = bspwm
; wm-restack = i3

; override-redirect = true

; This module is not active by default (to enable it, add it to one of the
; modules-* list above).
; Please note that only a single tray can exist at any time. If you launch
; multiple bars with this module, only a single one will show it, the others
; will produce a warning. Which bar gets the module is timing dependent and can
; be quite random.
; For more information, see the documentation page for this module:
; https://polybar.readthedocs.io/en/stable/user/modules/tray.html
[module/systray]
type = internal/tray

format-margin = 8pt
tray-spacing = 16pt

[module/xworkspaces]
type = internal/xworkspaces

label-active = %name%
label-active-background = ${colors.background-alt}
label-active-underline= ${colors.primary}
label-active-padding = 1

label-occupied = %name%
label-occupied-padding = 1

label-urgent = %name%
label-urgent-background = ${colors.alert}
label-urgent-padding = 1

label-empty = %name%
label-empty-foreground = ${colors.disabled}
label-empty-padding = 1

[module/xwindow]
type = internal/xwindow
label = %title:0:60:...%

[module/filesystem]
type = internal/fs
interval = 25
mount-0 = /
# This is the icon logic
format-mounted = <label-mounted>
format-mounted-prefix = "󰋊 "
format-mounted-prefix-foreground = ${colors.primary}

# What to show if the drive isn't found
format-unmounted = <label-unmounted>
format-unmounted-prefix = "󱁌 "
format-unmounted-prefix-foreground = ${colors.disabled}

label-mounted = %percentage_used%% × %total%
label-unmounted = %mountpoint% not mounted

[module/pulseaudio]
type = internal/pulseaudio

format-volume-prefix = "  "
format-volume-prefix-foreground = ${colors.primary}
format-volume = <label-volume>

label-volume = %percentage%%

label-muted = 󰖁
label-muted-foreground = ${colors.disabled}

[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock

label-layout = %layout%
label-layout-foreground = ${colors.primary}

label-indicator-padding = 2
label-indicator-margin = 1
label-indicator-foreground = ${colors.background}
label-indicator-background = ${colors.secondary}

[module/memory]
type = internal/memory
interval = 2
format-prefix = " "
format-prefix-foreground = ${colors.primary}
label = %percentage_used:2%%

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = "󰍛 "
format-prefix-foreground = ${colors.primary}
warn-percentage = 90
format = <label>
label = %percentage:2%%
format-warn = <label-warn>
label-warn = 󰍛  %percentage%%
label-warn-foreground = #ff5555
label-warn-background = #44475a
label-warn-padding = 1

[network-base]
type = internal/network
interval = 5
format-connected = <label-connected>
format-disconnected = <label-disconnected>
label-disconnected = %{F#F0C674}%ifname%%{F#707880} disconnected

[module/wlan]
inherit = network-base
interface-type = wireless

# Icon for the connected state
format-connected = <label-connected>
format-connected-prefix = "󰖩 "
format-connected-prefix-foreground = ${colors.primary}

# Icon for the disconnected state
format-disconnected = <label-disconnected>
format-disconnected-prefix = ""
format-disconnected-prefix-foreground = ${colors.disabled}

label-connected = %{F#F0C674}%essid%%{F-}
;%local_ip%
label-disconnected = %{F707880}󰖪 

[module/eth]
inherit = network-base
interface-type = wired
label-connected = %{F#F0C674}%ifname%%{F-} %local_ip%


[module/bluetooth]
type = custom/script
exec = ~/.config/polybar/scripts/bluetooth.sh
interval = 5

# Click to open a manager (blueman-manager is best for i3)

format-background = ${colors.background-alt}
format-padding = 1


[module/date]
type = internal/date
interval = 1

date = %H:%M:%S
date-alt = %A, %d %b %H:%M:%S

label = %date%
label-foreground = ${colors.primary}

[module/backlight]
type = internal/backlight
card = intel_backlight
use-actual-brightness = true
enable-scroll = true

format = <ramp> <label>
label = %percentage%%

ramp-0 = 󰃞
ramp-1 = 󰃟
ramp-2 = 󰃠
ramp-foreground = ${colors.primary}


[settings]
screenchange-reload = true
pseudo-transparency = true


[module/music]
type = custom/script
tail = true
interval = 1

# We add the buttons directly to the output string
exec = echo "$(~/.config/polybar/scripts/music.sh)"

; format-prefix = "󰐊 "
format-prefix-foreground = ${colors.primary}

click-left = playerctl play-pause
click-middle = playerctl previous
click-right = playerctl next

[module/battery]
type = internal/battery

# This allows the module to update whenever the system sends a power event
full-at = 99
low-at = 10

# Use the names you found in step 1
battery = BAT0
adapter = ADP1

# Disable polling if your system supports events (saves CPU)
poll-interval = 5

format-charging = <animation-charging> <label-charging>
label-charging = %percentage%%
animation-charging-0 = 
animation-charging-1 = 
animation-charging-2 = 
animation-charging-3 = 
animation-charging-4 = 
animation-charging-framerate = 750
animation-charging-foreground = #a8ff00

# 2. When Discharging
format-discharging = <ramp-capacity> <label-discharging>
label-discharging = %percentage%%
ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 
ramp-capacity-0-foreground = ${colors.alert}
ramp-capacity-foreground = ${colors.primary}

# 3. When Full
format-full-prefix = " "
format-full-prefix-foreground = #a8ff00
label-full = %percentage%%
; vim:ft=dosini

[module/powermenu]
type = custom/text
content = " "
content-foreground = ${colors.alert}
# This triggers a simple shell command
click-left = ~/.config/rofi/powermenu.sh

